export callIfExists from './callIfExists'
export perf from './perf'
export requestAnimationFrame, {cancelAnimationFrame} from './requestAnimationFrame'
export requestInterval, {clearRequestInterval} from './requestInterval'
export requestTimeout, {clearRequestTimeout} from './requestTimeout'
