import _callIfExists from './callIfExists';
export { _callIfExists as callIfExists };
import _perf from './perf';
export { _perf as perf };
import _requestAnimationFrame from './requestAnimationFrame';
export { _requestAnimationFrame as requestAnimationFrame };
export { cancelAnimationFrame } from './requestAnimationFrame';
import _requestInterval from './requestInterval';
export { _requestInterval as requestInterval };
export { clearRequestInterval } from './requestInterval';
import _requestTimeout from './requestTimeout';
export { _requestTimeout as requestTimeout };
export { clearRequestTimeout } from './requestTimeout';